name = "Test Modpack A"
author = "CinnamonBunniy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "424b22a7233c44698d9a4ecd0e19ceef6a7ddeea18eedb226317b1e74c115942"

[versions]
minecraft = "1.21.1"
quilt = "0.29.3-beta.1"
